name: pbconv
version: 0.5.5
author: Thomas Zhang <zhangtao@skyarm.com>
description: >-
  A implement of Dart:convert for [Protobuf](https://developers.google.com/protocol-buffers/).
homepage: https://github.com/skyarm/pbconv
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
dev_dependencies:

